[package]
name = "rust-minecraft-networking"
version = "0.1.0"
authors = ["Exopteron <exopteron@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deflate = "0.9.1"
compress = "0.2.1"
lzma-rs = "0.2.0"